import { Kol, KolDashboardRow } from './types'

export const mockKols: Kol[] = [
  {
    id: 'kol-001',
    name: 'Linh Nguyễn Beauty',
    channel_url: 'https://www.tiktok.com/@linhnguyen.beauty',
    platform: 'TikTok',
    category: 'Beauty & Skincare',
    follower_count: 1_250_000,
    contact: 'linhnguyen.beauty@gmail.com',
    status: 'ACTIVE',
    campaigns: [
      {
        id: 'c-001',
        kol_id: 'kol-001',
        campaign_name: 'Kem dưỡng ẩm Laneige T3/2024',
        collaboration_date: '2024-03-10',
        pic: 'Minh Anh',
        collab_type: 'VIDEO_REVIEW',
        platform: 'TikTok',
        booking_fee: 15_000_000,
        gmv: 185_000_000,
        views: 620_000,
        clicks: 31_000,
        orders: 1_350,
        revenue: 12_000_000,
        return_rate: 3.2,
        status: 'COMPLETED',
      },
      {
        id: 'c-002',
        kol_id: 'kol-001',
        campaign_name: 'Flash Sale Serum T4/2024',
        collaboration_date: '2024-04-20',
        pic: 'Minh Anh',
        collab_type: 'LIVESTREAM',
        platform: 'TikTok',
        booking_fee: 25_000_000,
        gmv: 320_000_000,
        views: 98_000,
        clicks: 45_000,
        orders: 3_200,
        revenue: 20_000_000,
        return_rate: 4.5,
        status: 'COMPLETED',
      },
      {
        id: 'c-003',
        kol_id: 'kol-001',
        campaign_name: 'Affiliate Shopee Mall T6/2024',
        collaboration_date: '2024-06-15',
        pic: 'Thu Hà',
        collab_type: 'AFFILIATE',
        platform: 'Shopee',
        booking_fee: 5_000_000,
        gmv: 95_000_000,
        views: 215_000,
        clicks: 19_000,
        orders: 890,
        revenue: 4_500_000,
        return_rate: 2.8,
        status: 'COMPLETED',
      },
    ],
  },
  {
    id: 'kol-002',
    name: 'Minh Tâm Fitness',
    channel_url: 'https://www.tiktok.com/@minhtam.fit',
    platform: 'TikTok',
    category: 'Fitness & Thể thao',
    follower_count: 2_100_000,
    contact: 'minhtam.fit@gmail.com',
    status: 'ACTIVE',
    campaigns: [
      {
        id: 'c-004',
        kol_id: 'kol-002',
        campaign_name: 'Review Whey Protein ON T2/2024',
        collaboration_date: '2024-02-18',
        pic: 'Đức Hùng',
        collab_type: 'VIDEO_REVIEW',
        platform: 'TikTok',
        booking_fee: 20_000_000,
        gmv: 250_000_000,
        views: 880_000,
        clicks: 42_000,
        orders: 2_100,
        revenue: 16_000_000,
        return_rate: 5.1,
        status: 'COMPLETED',
      },
      {
        id: 'c-005',
        kol_id: 'kol-002',
        campaign_name: 'Combo Video + Live Đồ Thể Thao T5/2024',
        collaboration_date: '2024-05-25',
        pic: 'Đức Hùng',
        collab_type: 'COMBO',
        platform: 'TikTok',
        booking_fee: 35_000_000,
        gmv: 480_000_000,
        views: 125_000,
        clicks: 58_000,
        orders: 4_200,
        revenue: 28_000_000,
        return_rate: 6.3,
        status: 'COMPLETED',
      },
    ],
  },
  {
    id: 'kol-003',
    name: 'Bếp Nhà Mình',
    channel_url: 'https://www.tiktok.com/@bepnhaminhcooks',
    platform: 'Both',
    category: 'Ẩm thực & Đồ dùng bếp',
    follower_count: 780_000,
    contact: 'bepnhaminh@gmail.com',
    status: 'ACTIVE',
    campaigns: [
      {
        id: 'c-006',
        kol_id: 'kol-003',
        campaign_name: 'Review Nồi Chiên Không Dầu T1/2024',
        collaboration_date: '2024-01-20',
        pic: 'Thu Hà',
        collab_type: 'VIDEO_REVIEW',
        platform: 'TikTok',
        booking_fee: 8_000_000,
        gmv: 72_000_000,
        views: 310_000,
        clicks: 22_000,
        orders: 680,
        revenue: 6_500_000,
        return_rate: 2.5,
        status: 'COMPLETED',
      },
      {
        id: 'c-007',
        kol_id: 'kol-003',
        campaign_name: 'Affiliate Gia vị Maggi T3/2024',
        collaboration_date: '2024-03-05',
        pic: 'Thanh Tú',
        collab_type: 'AFFILIATE',
        platform: 'Shopee',
        booking_fee: 3_000_000,
        gmv: 48_000_000,
        views: 185_000,
        clicks: 14_000,
        orders: 950,
        revenue: 2_800_000,
        return_rate: 3.1,
        status: 'COMPLETED',
      },
      {
        id: 'c-008',
        kol_id: 'kol-003',
        campaign_name: 'Livestream Shopee Mùa Hè T6/2024',
        collaboration_date: '2024-06-08',
        pic: 'Thu Hà',
        collab_type: 'LIVESTREAM',
        platform: 'Shopee',
        booking_fee: 12_000_000,
        gmv: 145_000_000,
        views: 62_000,
        clicks: 28_000,
        orders: 2_400,
        revenue: 10_000_000,
        return_rate: 4.2,
        status: 'COMPLETED',
      },
      {
        id: 'c-009',
        kol_id: 'kol-003',
        campaign_name: 'Affiliate Bộ nồi Tefal T8/2024',
        collaboration_date: '2024-08-12',
        pic: 'Thanh Tú',
        collab_type: 'AFFILIATE',
        platform: 'Shopee',
        booking_fee: 4_000_000,
        gmv: 62_000_000,
        views: 140_000,
        clicks: 11_000,
        orders: 520,
        revenue: 3_600_000,
        return_rate: 2.9,
        status: 'COMPLETED',
      },
    ],
  },
  {
    id: 'kol-004',
    name: 'Thùy Linh Style',
    channel_url: 'https://www.tiktok.com/@thuylinh.style',
    platform: 'Both',
    category: 'Thời trang & Lifestyle',
    follower_count: 3_400_000,
    contact: 'thuylinh.style@gmail.com',
    status: 'ACTIVE',
    campaigns: [
      {
        id: 'c-010',
        kol_id: 'kol-004',
        campaign_name: 'Review BST Hè Zara T4/2024',
        collaboration_date: '2024-04-05',
        pic: 'Minh Anh',
        collab_type: 'VIDEO_REVIEW',
        platform: 'TikTok',
        booking_fee: 40_000_000,
        gmv: 520_000_000,
        views: 1_800_000,
        clicks: 85_000,
        orders: 5_600,
        revenue: 32_000_000,
        return_rate: 12.4,
        status: 'COMPLETED',
      },
      {
        id: 'c-011',
        kol_id: 'kol-004',
        campaign_name: 'Livestream Thời Trang Hè T5/2024',
        collaboration_date: '2024-05-18',
        pic: 'Minh Anh',
        collab_type: 'LIVESTREAM',
        platform: 'TikTok',
        booking_fee: 55_000_000,
        gmv: 780_000_000,
        views: 210_000,
        clicks: 95_000,
        orders: 8_100,
        revenue: 45_000_000,
        return_rate: 14.8,
        status: 'COMPLETED',
      },
      {
        id: 'c-012',
        kol_id: 'kol-004',
        campaign_name: 'Combo TikTok + Shopee Thu Đông T9/2024',
        collaboration_date: '2024-09-10',
        pic: 'Thu Hà',
        collab_type: 'COMBO',
        platform: 'TikTok',
        booking_fee: 70_000_000,
        gmv: 1_200_000_000,
        views: 350_000,
        clicks: 120_000,
        orders: 11_500,
        revenue: 58_000_000,
        return_rate: 11.2,
        status: 'COMPLETED',
      },
    ],
  },
  {
    id: 'kol-005',
    name: 'TechReview VN',
    channel_url: 'https://shopee.vn/techreviewvn',
    platform: 'Shopee',
    category: 'Công nghệ & Điện tử',
    follower_count: 520_000,
    contact: 'techreviewvn@gmail.com',
    status: 'ACTIVE',
    campaigns: [
      {
        id: 'c-013',
        kol_id: 'kol-005',
        campaign_name: 'Review Tai nghe Sony WH-1000XM5 T3/2024',
        collaboration_date: '2024-03-22',
        pic: 'Đức Hùng',
        collab_type: 'VIDEO_REVIEW',
        platform: 'Shopee',
        booking_fee: 12_000_000,
        gmv: 95_000_000,
        views: 420_000,
        clicks: 28_000,
        orders: 850,
        revenue: 10_000_000,
        return_rate: 7.3,
        status: 'COMPLETED',
      },
      {
        id: 'c-014',
        kol_id: 'kol-005',
        campaign_name: 'Affiliate Samsung Galaxy S24 T5/2024',
        collaboration_date: '2024-05-10',
        pic: 'Thanh Tú',
        collab_type: 'AFFILIATE',
        platform: 'Shopee',
        booking_fee: 8_000_000,
        gmv: 185_000_000,
        views: 560_000,
        clicks: 35_000,
        orders: 620,
        revenue: 7_200_000,
        return_rate: 6.8,
        status: 'COMPLETED',
      },
    ],
  },
  {
    id: 'kol-006',
    name: 'Cuộc Sống Xanh',
    channel_url: 'https://www.tiktok.com/@cuocsongxanh.vn',
    platform: 'TikTok',
    category: 'Lifestyle & Wellness',
    follower_count: 340_000,
    contact: 'cuocsongxanh.vn@gmail.com',
    status: 'INACTIVE',
    notes: 'Tạm dừng hợp tác từ Q3/2024, đang đàm phán lại hợp đồng',
    campaigns: [
      {
        id: 'c-015',
        kol_id: 'kol-006',
        campaign_name: 'Review Máy Lọc Không Khí Xiaomi T2/2024',
        collaboration_date: '2024-02-14',
        pic: 'Thanh Tú',
        collab_type: 'VIDEO_REVIEW',
        platform: 'TikTok',
        booking_fee: 8_000_000,
        gmv: 45_000_000,
        views: 180_000,
        clicks: 12_000,
        orders: 380,
        revenue: 6_500_000,
        return_rate: 4.1,
        status: 'COMPLETED',
      },
    ],
  },
]

// Helper: transform Kol[] → KolDashboardRow[] for the table
export function buildDashboardRows(kols: Kol[]): KolDashboardRow[] {
  return kols.map((kol, index) => {
    const campaigns = kol.campaigns
    const total_campaigns = campaigns.length
    const collab_types = Array.from(new Set(campaigns.map((c) => c.collab_type)))
    const pics = Array.from(new Set(campaigns.map((c) => c.pic)))
    const total_booking_fee = campaigns.reduce((sum, c) => sum + c.booking_fee, 0)
    const total_gmv = campaigns.reduce((sum, c) => sum + (c.gmv ?? 0), 0)
    const gmv_per_campaign = total_campaigns > 0 ? total_gmv / total_campaigns : 0

    return {
      id: kol.id,
      stt: index + 1,
      name: kol.name,
      channel_url: kol.channel_url,
      platform: kol.platform,
      category: kol.category,
      status: kol.status,
      total_campaigns,
      collab_types,
      pics,
      total_booking_fee,
      total_gmv,
      gmv_per_campaign,
    }
  })
}

// Helper: aggregate stats for the summary cards
export function getDashboardStats(kols: Kol[]) {
  const activeKols = kols.filter((k) => k.status === 'ACTIVE').length
  const allCampaigns = kols.flatMap((k) => k.campaigns)
  const totalCampaigns = allCampaigns.length
  const totalBookingFee = allCampaigns.reduce((sum, c) => sum + c.booking_fee, 0)
  const totalGmv = allCampaigns.reduce((sum, c) => sum + (c.gmv ?? 0), 0)
  return { activeKols, totalKols: kols.length, totalCampaigns, totalBookingFee, totalGmv }
}
